// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi_B0vV2mbwNPsPg6SLxaUyeeOAv-byE0',
    appId: '1:979384440853:web:dd84fd29383d73f929161c',
    messagingSenderId: '979384440853',
    projectId: 'flash-chat-dbe0c',
    authDomain: 'flash-chat-dbe0c.firebaseapp.com',
    storageBucket: 'flash-chat-dbe0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcMVDl_oSpGCYq9cEUWu5NZ6TO9xUxcCE',
    appId: '1:979384440853:android:37b364c0bfa89f8329161c',
    messagingSenderId: '979384440853',
    projectId: 'flash-chat-dbe0c',
    storageBucket: 'flash-chat-dbe0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYarSMyhSN7RmIm3ndAdgxDazYK9nENqA',
    appId: '1:979384440853:ios:687ede467ec3b1ad29161c',
    messagingSenderId: '979384440853',
    projectId: 'flash-chat-dbe0c',
    storageBucket: 'flash-chat-dbe0c.appspot.com',
    iosClientId: '979384440853-2a8j72pm1nd9sk8tdn92s3jqe2upok21.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatStartingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYarSMyhSN7RmIm3ndAdgxDazYK9nENqA',
    appId: '1:979384440853:ios:687ede467ec3b1ad29161c',
    messagingSenderId: '979384440853',
    projectId: 'flash-chat-dbe0c',
    storageBucket: 'flash-chat-dbe0c.appspot.com',
    iosClientId: '979384440853-2a8j72pm1nd9sk8tdn92s3jqe2upok21.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatStartingProject',
  );
}
